### ISSUE TITLE
GP possible overestimates uncertainty?

### ISSUE THREAD

**Issue by sebbleroni** [michaelhush/M-LOOP#83] opened 2020-12-15 15:19 UTC
**Describe the bug**
I was realizing that M-LOOP seems to be overestimating the uncertainty in the presence of noise, both in real experiments and on synthetic data. To illustrate this I try to optimize a "experiment" in which I can easily control the level of noise. While being able to fit the function quite well, the uncertainty seems to greatly exceed the seen data. Furthermore, if I fit the data "by hand" using the hyperparameters from M-LOOP, the uncertainty seems to be more realistic. I am worried that this will affect the performance in the real experiment, so I wanted to ask if this behavior is to be expected.

**To Reproduce**
```python
#Imports for M-LOOP
import mloop.interfaces as mli
import mloop.controllers as mlc
import mloop.visualizations as mlv
import mloop.utilities as mlu

# sklearn imports
import sklearn.gaussian_process as skg
import sklearn.gaussian_process.kernels as skk

import numpy as np
import matplotlib.pyplot as plt

import sys
noise_level = float(sys.argv[1])

input_dict = {
    'max_num_runs' : 30, 
    'num_params' : 1, 
    'min_boundary' : [0],
    'max_boundary' : [1],
    'cost_has_noise' : True
}

with open("cost.npy", 'rb') as file:
    cost_array = np.load(file)
    params_array = np.linspace(0, 1, len(cost_array))

def cost_fct(x, xp, yp, noise):
    res = np.interp(x, xp, yp)
    res += np.random.normal(0, noise)
    return res

class CustomInterface(mli.Interface):
    
    def __init__(self):
        super(CustomInterface,self).__init__()

    def get_next_cost_dict(self,params_dict):
        
        params = params_dict['params']
        
        cost = cost_fct(params[0],  params_array,cost_array, noise_level)
        uncer = 0
        bad = False
        
        cost_dict = {'cost':cost, 'uncer':uncer, 'bad':bad}
        return cost_dict
    
def main():

    print(cost_array, )
    
    interface = CustomInterface()
    controller = mlc.create_controller(interface, **input_dict)
    controller.optimize() 
    
    # visualization
    vis = mlv.GaussianProcessVisualizer(controller.ml_learner.total_archive_filename)
    vis.plot_cross_sections()

    # plotting
    plt.figure(1)
    plt.scatter(controller.out_params, controller.in_costs, label="sampled data")
    plt.plot(params_array, cost_array, '-', label="true data")
    plt.title("Landscape M-LOOP (noise = %0.3f)" % noise_level)
    plt.legend()

    # manual fit
    gp_kernel = skk.RBF(vis.length_scale)
    gp_kernel += skk.WhiteKernel(vis.noise_level)
    alpha = vis.all_uncers**2
    gaussian_process = skg.GaussianProcessRegressor(kernel=gp_kernel, n_restarts_optimizer=10)
    gaussian_process.fit(vis.all_params,vis.all_costs)
    params = np.linspace(0, 1, 100).reshape(-1, 1)
    (cost, uncer) = gaussian_process.predict(params, return_std=True)

    #plotting
    plt.figure(2)
    plt.title("Landscape (noise = %0.3f)")
    plt.plot(params, cost, 'r-', label="fit")
    plt.plot(params,cost+uncer, 'r--')
    plt.plot(params, cost-uncer, 'r--')
    plt.scatter(controller.out_params, controller.in_costs, label="sampled data")
    plt.plot(params_array, cost_array, '-', label="true data")
    plt.title("Landscape M-LOOP (noise = %0.3f)" % noise_level)
    plt.xlim(0, 1)
    plt.legend()
    
    plt.show()

if __name__ == '__main__':
    main()
```

**Expected behavior**
Good fits, but very large uncertainty
![landscape_mloop_fit_0p010](https://user-images.githubusercontent.com/70020179/102233732-ddd92200-3ef0-11eb-8836-52f071b9d203.png)
![landscape_own_fit_0p010](https://user-images.githubusercontent.com/70020179/102234021-25f84480-3ef1-11eb-8923-2dd9e96d38c0.png)

- OS: Linux Ubuntu 16.04, 20.04
- M-LOOP 3.1.1
- Python 3.5.2 & 3.8

**Comment by zakv** [comment] 2020-12-15 19:55
Hmm. I recently worked on a few issues related to uncertainties with the Gaussian process learner (PR's #72, #73, #74, #78), and some of the issues fixed by #72 in particular seem like they might be the cause the of behavior here.

We haven't released a new version of M-LOOP since those pull requests though, so would it be possible for you to install the latest version from the github then run this test again? From your examples it seems like you have a good grasp of what's going on, so I think you'd benefit from having an editable install that you could play around with anyway.

**Comment by sebbleroni** [comment] 2020-12-15 22:51
I pulled the version from github et voilà, it worked perfectly, see the attached picture. The current commit was #79 in case someone find this issue a some later point.

Thanks to @zakv for the suggestions!

![landscape_mloop_fit](https://user-images.githubusercontent.com/70020179/102282101-5ca17f80-3f30-11eb-9291-d79b37b7816a.png)
![landscape_own_fit](https://user-images.githubusercontent.com/70020179/102282103-5d3a1600-3f30-11eb-8737-d44e5c771a0a.png)

**Comment by charmasaur** [comment] 2020-12-15 22:56
Thanks for the report and verification, and thanks Zak for the pre-emptive fixes!

**Comment by zakv** [comment] 2020-12-15 23:22
Good to hear! Sounds like this issue is resolved so I'll close it

**Closed by zakv** 2020-12-15 23:22 UTC
